import React from "react";
import type { Metadata } from "next";
import { Fonts } from "@/constants";
import ReactQueryWrapper from "@/app/_components/ReactQueryWrapper/ReactQueryWrapper";
import { AuthProvider } from "@/contexts/AuthCtx/AuthCtx";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App", // TODO
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="fr">
			<body className={Fonts.CLASSNAMES}>
				<noscript>
					Vous avez besoin de JavaScript pour accéder à la page Web. {/* TODO */}
				</noscript>

				<ReactQueryWrapper>
					<AuthProvider>
						<React.StrictMode>
							{children}
						</React.StrictMode>
					</AuthProvider>
				</ReactQueryWrapper>
			</body>
		</html>
	);
}
