import React from "react";
import clsx from "clsx";
import type { Metadata } from "next";
import { Fonts } from "@/constants";
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";
import ReactQueryWrapper from "@/app/_components/ReactQueryWrapper/ReactQueryWrapper";
import { AuthProvider } from "@/contexts/AuthCtx/AuthCtx";
import Header from "@/app/_components/Header/Header";
import { App } from "@/constants";
import "./globals.css";

export const metadata: Metadata = {
	title: App.APP_NAME,
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="fr">
			<body className={clsx(Fonts.notoSans.className, "text-foreground bg-background")}>
				<noscript>
					Vous avez besoin de JavaScript pour accéder à la page Web. {/* TODO */}
				</noscript>

				<Toaster/>

				<Providers>
					<ReactQueryWrapper>
						<AuthProvider>
							<React.StrictMode>
								<div style={{ display: "flex", flexDirection: "column", width: "100%", height: "100%", overflow: "auto" }}>
									<Header/>

									{children}
								</div>
							</React.StrictMode>
						</AuthProvider>
					</ReactQueryWrapper>
				</Providers>
			</body>
		</html>
	);
}
